/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated.app.preferences'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'
import { Route as AuthenticatedAppPPlannerIdRouteImport } from './routes/_authenticated.app.p.$plannerId'
import { Route as AuthenticatedAppPPlannerIdVaultRouteImport } from './routes/_authenticated.app.p.$plannerId.vault'
import { Route as AuthenticatedAppPPlannerIdTimelineRouteImport } from './routes/_authenticated.app.p.$plannerId.timeline'
import { Route as AuthenticatedAppPPlannerIdReportsRouteImport } from './routes/_authenticated.app.p.$plannerId.reports'
import { Route as AuthenticatedAppPPlannerIdProjectsRouteImport } from './routes/_authenticated.app.p.$plannerId.projects'
import { Route as AuthenticatedAppPPlannerIdNotificationsRouteImport } from './routes/_authenticated.app.p.$plannerId.notifications'
import { Route as AuthenticatedAppPPlannerIdNotesRouteImport } from './routes/_authenticated.app.p.$plannerId.notes'
import { Route as AuthenticatedAppPPlannerIdMonthlyRouteImport } from './routes/_authenticated.app.p.$plannerId.monthly'
import { Route as AuthenticatedAppPPlannerIdInvoicesRouteImport } from './routes/_authenticated.app.p.$plannerId.invoices'
import { Route as AuthenticatedAppPPlannerIdInvestmentsRouteImport } from './routes/_authenticated.app.p.$plannerId.investments'
import { Route as AuthenticatedAppPPlannerIdIncomeRouteImport } from './routes/_authenticated.app.p.$plannerId.income'
import { Route as AuthenticatedAppPPlannerIdGoalsRouteImport } from './routes/_authenticated.app.p.$plannerId.goals'
import { Route as AuthenticatedAppPPlannerIdExpensesRouteImport } from './routes/_authenticated.app.p.$plannerId.expenses'
import { Route as AuthenticatedAppPPlannerIdDashboardRouteImport } from './routes/_authenticated.app.p.$plannerId.dashboard'
import { Route as AuthenticatedAppPPlannerIdClientsRouteImport } from './routes/_authenticated.app.p.$plannerId.clients'
import { Route as AuthenticatedAppPPlannerIdChartsRouteImport } from './routes/_authenticated.app.p.$plannerId.charts'
import { Route as AuthenticatedAppPPlannerIdCashflowRouteImport } from './routes/_authenticated.app.p.$plannerId.cashflow'
import { Route as AuthenticatedAppPPlannerIdBudgetRouteImport } from './routes/_authenticated.app.p.$plannerId.budget'
import { Route as AuthenticatedAppPPlannerIdAccountsRouteImport } from './routes/_authenticated.app.p.$plannerId.accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPPlannerIdRoute =
  AuthenticatedAppPPlannerIdRouteImport.update({
    id: '/p/$plannerId',
    path: '/p/$plannerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPPlannerIdVaultRoute =
  AuthenticatedAppPPlannerIdVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdTimelineRoute =
  AuthenticatedAppPPlannerIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdReportsRoute =
  AuthenticatedAppPPlannerIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdProjectsRoute =
  AuthenticatedAppPPlannerIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdNotificationsRoute =
  AuthenticatedAppPPlannerIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdNotesRoute =
  AuthenticatedAppPPlannerIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdMonthlyRoute =
  AuthenticatedAppPPlannerIdMonthlyRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdInvoicesRoute =
  AuthenticatedAppPPlannerIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdInvestmentsRoute =
  AuthenticatedAppPPlannerIdInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdIncomeRoute =
  AuthenticatedAppPPlannerIdIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdGoalsRoute =
  AuthenticatedAppPPlannerIdGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdExpensesRoute =
  AuthenticatedAppPPlannerIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdDashboardRoute =
  AuthenticatedAppPPlannerIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdClientsRoute =
  AuthenticatedAppPPlannerIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdChartsRoute =
  AuthenticatedAppPPlannerIdChartsRouteImport.update({
    id: '/charts',
    path: '/charts',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdCashflowRoute =
  AuthenticatedAppPPlannerIdCashflowRouteImport.update({
    id: '/cashflow',
    path: '/cashflow',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdBudgetRoute =
  AuthenticatedAppPPlannerIdBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)
const AuthenticatedAppPPlannerIdAccountsRoute =
  AuthenticatedAppPPlannerIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAppPPlannerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/p/$plannerId': typeof AuthenticatedAppPPlannerIdRouteWithChildren
  '/app/p/$plannerId/accounts': typeof AuthenticatedAppPPlannerIdAccountsRoute
  '/app/p/$plannerId/budget': typeof AuthenticatedAppPPlannerIdBudgetRoute
  '/app/p/$plannerId/cashflow': typeof AuthenticatedAppPPlannerIdCashflowRoute
  '/app/p/$plannerId/charts': typeof AuthenticatedAppPPlannerIdChartsRoute
  '/app/p/$plannerId/clients': typeof AuthenticatedAppPPlannerIdClientsRoute
  '/app/p/$plannerId/dashboard': typeof AuthenticatedAppPPlannerIdDashboardRoute
  '/app/p/$plannerId/expenses': typeof AuthenticatedAppPPlannerIdExpensesRoute
  '/app/p/$plannerId/goals': typeof AuthenticatedAppPPlannerIdGoalsRoute
  '/app/p/$plannerId/income': typeof AuthenticatedAppPPlannerIdIncomeRoute
  '/app/p/$plannerId/investments': typeof AuthenticatedAppPPlannerIdInvestmentsRoute
  '/app/p/$plannerId/invoices': typeof AuthenticatedAppPPlannerIdInvoicesRoute
  '/app/p/$plannerId/monthly': typeof AuthenticatedAppPPlannerIdMonthlyRoute
  '/app/p/$plannerId/notes': typeof AuthenticatedAppPPlannerIdNotesRoute
  '/app/p/$plannerId/notifications': typeof AuthenticatedAppPPlannerIdNotificationsRoute
  '/app/p/$plannerId/projects': typeof AuthenticatedAppPPlannerIdProjectsRoute
  '/app/p/$plannerId/reports': typeof AuthenticatedAppPPlannerIdReportsRoute
  '/app/p/$plannerId/timeline': typeof AuthenticatedAppPPlannerIdTimelineRoute
  '/app/p/$plannerId/vault': typeof AuthenticatedAppPPlannerIdVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/p/$plannerId': typeof AuthenticatedAppPPlannerIdRouteWithChildren
  '/app/p/$plannerId/accounts': typeof AuthenticatedAppPPlannerIdAccountsRoute
  '/app/p/$plannerId/budget': typeof AuthenticatedAppPPlannerIdBudgetRoute
  '/app/p/$plannerId/cashflow': typeof AuthenticatedAppPPlannerIdCashflowRoute
  '/app/p/$plannerId/charts': typeof AuthenticatedAppPPlannerIdChartsRoute
  '/app/p/$plannerId/clients': typeof AuthenticatedAppPPlannerIdClientsRoute
  '/app/p/$plannerId/dashboard': typeof AuthenticatedAppPPlannerIdDashboardRoute
  '/app/p/$plannerId/expenses': typeof AuthenticatedAppPPlannerIdExpensesRoute
  '/app/p/$plannerId/goals': typeof AuthenticatedAppPPlannerIdGoalsRoute
  '/app/p/$plannerId/income': typeof AuthenticatedAppPPlannerIdIncomeRoute
  '/app/p/$plannerId/investments': typeof AuthenticatedAppPPlannerIdInvestmentsRoute
  '/app/p/$plannerId/invoices': typeof AuthenticatedAppPPlannerIdInvoicesRoute
  '/app/p/$plannerId/monthly': typeof AuthenticatedAppPPlannerIdMonthlyRoute
  '/app/p/$plannerId/notes': typeof AuthenticatedAppPPlannerIdNotesRoute
  '/app/p/$plannerId/notifications': typeof AuthenticatedAppPPlannerIdNotificationsRoute
  '/app/p/$plannerId/projects': typeof AuthenticatedAppPPlannerIdProjectsRoute
  '/app/p/$plannerId/reports': typeof AuthenticatedAppPPlannerIdReportsRoute
  '/app/p/$plannerId/timeline': typeof AuthenticatedAppPPlannerIdTimelineRoute
  '/app/p/$plannerId/vault': typeof AuthenticatedAppPPlannerIdVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/p/$plannerId': typeof AuthenticatedAppPPlannerIdRouteWithChildren
  '/_authenticated/app/p/$plannerId/accounts': typeof AuthenticatedAppPPlannerIdAccountsRoute
  '/_authenticated/app/p/$plannerId/budget': typeof AuthenticatedAppPPlannerIdBudgetRoute
  '/_authenticated/app/p/$plannerId/cashflow': typeof AuthenticatedAppPPlannerIdCashflowRoute
  '/_authenticated/app/p/$plannerId/charts': typeof AuthenticatedAppPPlannerIdChartsRoute
  '/_authenticated/app/p/$plannerId/clients': typeof AuthenticatedAppPPlannerIdClientsRoute
  '/_authenticated/app/p/$plannerId/dashboard': typeof AuthenticatedAppPPlannerIdDashboardRoute
  '/_authenticated/app/p/$plannerId/expenses': typeof AuthenticatedAppPPlannerIdExpensesRoute
  '/_authenticated/app/p/$plannerId/goals': typeof AuthenticatedAppPPlannerIdGoalsRoute
  '/_authenticated/app/p/$plannerId/income': typeof AuthenticatedAppPPlannerIdIncomeRoute
  '/_authenticated/app/p/$plannerId/investments': typeof AuthenticatedAppPPlannerIdInvestmentsRoute
  '/_authenticated/app/p/$plannerId/invoices': typeof AuthenticatedAppPPlannerIdInvoicesRoute
  '/_authenticated/app/p/$plannerId/monthly': typeof AuthenticatedAppPPlannerIdMonthlyRoute
  '/_authenticated/app/p/$plannerId/notes': typeof AuthenticatedAppPPlannerIdNotesRoute
  '/_authenticated/app/p/$plannerId/notifications': typeof AuthenticatedAppPPlannerIdNotificationsRoute
  '/_authenticated/app/p/$plannerId/projects': typeof AuthenticatedAppPPlannerIdProjectsRoute
  '/_authenticated/app/p/$plannerId/reports': typeof AuthenticatedAppPPlannerIdReportsRoute
  '/_authenticated/app/p/$plannerId/timeline': typeof AuthenticatedAppPPlannerIdTimelineRoute
  '/_authenticated/app/p/$plannerId/vault': typeof AuthenticatedAppPPlannerIdVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/preferences'
    | '/app/profile'
    | '/app/p/$plannerId'
    | '/app/p/$plannerId/accounts'
    | '/app/p/$plannerId/budget'
    | '/app/p/$plannerId/cashflow'
    | '/app/p/$plannerId/charts'
    | '/app/p/$plannerId/clients'
    | '/app/p/$plannerId/dashboard'
    | '/app/p/$plannerId/expenses'
    | '/app/p/$plannerId/goals'
    | '/app/p/$plannerId/income'
    | '/app/p/$plannerId/investments'
    | '/app/p/$plannerId/invoices'
    | '/app/p/$plannerId/monthly'
    | '/app/p/$plannerId/notes'
    | '/app/p/$plannerId/notifications'
    | '/app/p/$plannerId/projects'
    | '/app/p/$plannerId/reports'
    | '/app/p/$plannerId/timeline'
    | '/app/p/$plannerId/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/preferences'
    | '/app/profile'
    | '/app/p/$plannerId'
    | '/app/p/$plannerId/accounts'
    | '/app/p/$plannerId/budget'
    | '/app/p/$plannerId/cashflow'
    | '/app/p/$plannerId/charts'
    | '/app/p/$plannerId/clients'
    | '/app/p/$plannerId/dashboard'
    | '/app/p/$plannerId/expenses'
    | '/app/p/$plannerId/goals'
    | '/app/p/$plannerId/income'
    | '/app/p/$plannerId/investments'
    | '/app/p/$plannerId/invoices'
    | '/app/p/$plannerId/monthly'
    | '/app/p/$plannerId/notes'
    | '/app/p/$plannerId/notifications'
    | '/app/p/$plannerId/projects'
    | '/app/p/$plannerId/reports'
    | '/app/p/$plannerId/timeline'
    | '/app/p/$plannerId/vault'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/p/$plannerId'
    | '/_authenticated/app/p/$plannerId/accounts'
    | '/_authenticated/app/p/$plannerId/budget'
    | '/_authenticated/app/p/$plannerId/cashflow'
    | '/_authenticated/app/p/$plannerId/charts'
    | '/_authenticated/app/p/$plannerId/clients'
    | '/_authenticated/app/p/$plannerId/dashboard'
    | '/_authenticated/app/p/$plannerId/expenses'
    | '/_authenticated/app/p/$plannerId/goals'
    | '/_authenticated/app/p/$plannerId/income'
    | '/_authenticated/app/p/$plannerId/investments'
    | '/_authenticated/app/p/$plannerId/invoices'
    | '/_authenticated/app/p/$plannerId/monthly'
    | '/_authenticated/app/p/$plannerId/notes'
    | '/_authenticated/app/p/$plannerId/notifications'
    | '/_authenticated/app/p/$plannerId/projects'
    | '/_authenticated/app/p/$plannerId/reports'
    | '/_authenticated/app/p/$plannerId/timeline'
    | '/_authenticated/app/p/$plannerId/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$plannerId': {
      id: '/_authenticated/app/p/$plannerId'
      path: '/p/$plannerId'
      fullPath: '/app/p/$plannerId'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$plannerId/vault': {
      id: '/_authenticated/app/p/$plannerId/vault'
      path: '/vault'
      fullPath: '/app/p/$plannerId/vault'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdVaultRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/timeline': {
      id: '/_authenticated/app/p/$plannerId/timeline'
      path: '/timeline'
      fullPath: '/app/p/$plannerId/timeline'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdTimelineRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/reports': {
      id: '/_authenticated/app/p/$plannerId/reports'
      path: '/reports'
      fullPath: '/app/p/$plannerId/reports'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdReportsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/projects': {
      id: '/_authenticated/app/p/$plannerId/projects'
      path: '/projects'
      fullPath: '/app/p/$plannerId/projects'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdProjectsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/notifications': {
      id: '/_authenticated/app/p/$plannerId/notifications'
      path: '/notifications'
      fullPath: '/app/p/$plannerId/notifications'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/notes': {
      id: '/_authenticated/app/p/$plannerId/notes'
      path: '/notes'
      fullPath: '/app/p/$plannerId/notes'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdNotesRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/monthly': {
      id: '/_authenticated/app/p/$plannerId/monthly'
      path: '/monthly'
      fullPath: '/app/p/$plannerId/monthly'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdMonthlyRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/invoices': {
      id: '/_authenticated/app/p/$plannerId/invoices'
      path: '/invoices'
      fullPath: '/app/p/$plannerId/invoices'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/investments': {
      id: '/_authenticated/app/p/$plannerId/investments'
      path: '/investments'
      fullPath: '/app/p/$plannerId/investments'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdInvestmentsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/income': {
      id: '/_authenticated/app/p/$plannerId/income'
      path: '/income'
      fullPath: '/app/p/$plannerId/income'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdIncomeRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/goals': {
      id: '/_authenticated/app/p/$plannerId/goals'
      path: '/goals'
      fullPath: '/app/p/$plannerId/goals'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdGoalsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/expenses': {
      id: '/_authenticated/app/p/$plannerId/expenses'
      path: '/expenses'
      fullPath: '/app/p/$plannerId/expenses'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdExpensesRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/dashboard': {
      id: '/_authenticated/app/p/$plannerId/dashboard'
      path: '/dashboard'
      fullPath: '/app/p/$plannerId/dashboard'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdDashboardRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/clients': {
      id: '/_authenticated/app/p/$plannerId/clients'
      path: '/clients'
      fullPath: '/app/p/$plannerId/clients'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdClientsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/charts': {
      id: '/_authenticated/app/p/$plannerId/charts'
      path: '/charts'
      fullPath: '/app/p/$plannerId/charts'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdChartsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/cashflow': {
      id: '/_authenticated/app/p/$plannerId/cashflow'
      path: '/cashflow'
      fullPath: '/app/p/$plannerId/cashflow'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdCashflowRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/budget': {
      id: '/_authenticated/app/p/$plannerId/budget'
      path: '/budget'
      fullPath: '/app/p/$plannerId/budget'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdBudgetRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
    '/_authenticated/app/p/$plannerId/accounts': {
      id: '/_authenticated/app/p/$plannerId/accounts'
      path: '/accounts'
      fullPath: '/app/p/$plannerId/accounts'
      preLoaderRoute: typeof AuthenticatedAppPPlannerIdAccountsRouteImport
      parentRoute: typeof AuthenticatedAppPPlannerIdRoute
    }
  }
}

interface AuthenticatedAppPPlannerIdRouteChildren {
  AuthenticatedAppPPlannerIdAccountsRoute: typeof AuthenticatedAppPPlannerIdAccountsRoute
  AuthenticatedAppPPlannerIdBudgetRoute: typeof AuthenticatedAppPPlannerIdBudgetRoute
  AuthenticatedAppPPlannerIdCashflowRoute: typeof AuthenticatedAppPPlannerIdCashflowRoute
  AuthenticatedAppPPlannerIdChartsRoute: typeof AuthenticatedAppPPlannerIdChartsRoute
  AuthenticatedAppPPlannerIdClientsRoute: typeof AuthenticatedAppPPlannerIdClientsRoute
  AuthenticatedAppPPlannerIdDashboardRoute: typeof AuthenticatedAppPPlannerIdDashboardRoute
  AuthenticatedAppPPlannerIdExpensesRoute: typeof AuthenticatedAppPPlannerIdExpensesRoute
  AuthenticatedAppPPlannerIdGoalsRoute: typeof AuthenticatedAppPPlannerIdGoalsRoute
  AuthenticatedAppPPlannerIdIncomeRoute: typeof AuthenticatedAppPPlannerIdIncomeRoute
  AuthenticatedAppPPlannerIdInvestmentsRoute: typeof AuthenticatedAppPPlannerIdInvestmentsRoute
  AuthenticatedAppPPlannerIdInvoicesRoute: typeof AuthenticatedAppPPlannerIdInvoicesRoute
  AuthenticatedAppPPlannerIdMonthlyRoute: typeof AuthenticatedAppPPlannerIdMonthlyRoute
  AuthenticatedAppPPlannerIdNotesRoute: typeof AuthenticatedAppPPlannerIdNotesRoute
  AuthenticatedAppPPlannerIdNotificationsRoute: typeof AuthenticatedAppPPlannerIdNotificationsRoute
  AuthenticatedAppPPlannerIdProjectsRoute: typeof AuthenticatedAppPPlannerIdProjectsRoute
  AuthenticatedAppPPlannerIdReportsRoute: typeof AuthenticatedAppPPlannerIdReportsRoute
  AuthenticatedAppPPlannerIdTimelineRoute: typeof AuthenticatedAppPPlannerIdTimelineRoute
  AuthenticatedAppPPlannerIdVaultRoute: typeof AuthenticatedAppPPlannerIdVaultRoute
}

const AuthenticatedAppPPlannerIdRouteChildren: AuthenticatedAppPPlannerIdRouteChildren =
  {
    AuthenticatedAppPPlannerIdAccountsRoute:
      AuthenticatedAppPPlannerIdAccountsRoute,
    AuthenticatedAppPPlannerIdBudgetRoute:
      AuthenticatedAppPPlannerIdBudgetRoute,
    AuthenticatedAppPPlannerIdCashflowRoute:
      AuthenticatedAppPPlannerIdCashflowRoute,
    AuthenticatedAppPPlannerIdChartsRoute:
      AuthenticatedAppPPlannerIdChartsRoute,
    AuthenticatedAppPPlannerIdClientsRoute:
      AuthenticatedAppPPlannerIdClientsRoute,
    AuthenticatedAppPPlannerIdDashboardRoute:
      AuthenticatedAppPPlannerIdDashboardRoute,
    AuthenticatedAppPPlannerIdExpensesRoute:
      AuthenticatedAppPPlannerIdExpensesRoute,
    AuthenticatedAppPPlannerIdGoalsRoute: AuthenticatedAppPPlannerIdGoalsRoute,
    AuthenticatedAppPPlannerIdIncomeRoute:
      AuthenticatedAppPPlannerIdIncomeRoute,
    AuthenticatedAppPPlannerIdInvestmentsRoute:
      AuthenticatedAppPPlannerIdInvestmentsRoute,
    AuthenticatedAppPPlannerIdInvoicesRoute:
      AuthenticatedAppPPlannerIdInvoicesRoute,
    AuthenticatedAppPPlannerIdMonthlyRoute:
      AuthenticatedAppPPlannerIdMonthlyRoute,
    AuthenticatedAppPPlannerIdNotesRoute: AuthenticatedAppPPlannerIdNotesRoute,
    AuthenticatedAppPPlannerIdNotificationsRoute:
      AuthenticatedAppPPlannerIdNotificationsRoute,
    AuthenticatedAppPPlannerIdProjectsRoute:
      AuthenticatedAppPPlannerIdProjectsRoute,
    AuthenticatedAppPPlannerIdReportsRoute:
      AuthenticatedAppPPlannerIdReportsRoute,
    AuthenticatedAppPPlannerIdTimelineRoute:
      AuthenticatedAppPPlannerIdTimelineRoute,
    AuthenticatedAppPPlannerIdVaultRoute: AuthenticatedAppPPlannerIdVaultRoute,
  }

const AuthenticatedAppPPlannerIdRouteWithChildren =
  AuthenticatedAppPPlannerIdRoute._addFileChildren(
    AuthenticatedAppPPlannerIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppPPlannerIdRoute: typeof AuthenticatedAppPPlannerIdRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppPPlannerIdRoute: AuthenticatedAppPPlannerIdRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
